version: '3.8'

services:
  discord-bot:
    build: .
    container_name: islamic-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs  
    networks:
      - bot-network
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  bot-network:
    driver: bridge
